### PR TITLE
0.7 updates

### PR DESCRIPTION
**Pull request by Roboneet**
depends on Keno/ASTInterpreter2.jl#29

### CODE REVIEW

**Comment by MikeInnes** [comment]
Cool! Happy to take this once the upstream PR is merged.

**Comment by MikeInnes** [comment]
Gave you commit, so you are welcome to merge and tag as you need to.

**Comment by Roboneet** [comment]
Thanks! I think its best to tag after `ASTInterpreter2.jl`/`JuliaInterpreter.jl` gets tagged.

**Comment by MikeInnes** [comment]
Looks like JuliaInterpreter is out, time to revive this?

**Pull request merged**
